services:
  backend:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    ports:
      - "3003:3003"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DB_HOST=db
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=3003
      - SECRET=${SECRET}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./api
          target: /usr/src/app
          ignore:
            - node_modules/
            - .git/

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API=http://backend:3003
    command: npm start
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/src/app
          ignore:
            - node_modules/
            - .git/


  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: