PATCH  http://localhost:3003/api/movies/1/addDirector
Content-Type: application/json

{
    "director": 2
}

// URL structure ->   api/movies/:movieId/addDirector

// Since this is a PATCH request, there's no need to send all the fields.
// This request will update only the sent data