PATCH  http://localhost:3003/api/movies/1/addProducer
Content-Type: application/json

{
    "producer": 1
}

// URL structure ->   api/movies/:movieId/addProducer

// Since this is a PATCH request, there's no need to send all the fields.
// This request will update only the sent data