PUT http://localhost:3003/api/movies/1
Content-Type: application/json

{
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "year": 2001
}

// URL structure ->   api/movies/:movieId