# Usar una imagen base oficial de Node.js
FROM node:18-alpine

# Crear y establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos del proyecto
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Exponer el puerto en el que el backend está escuchando
EXPOSE 3003

# Comando para iniciar el servidor
CMD ["npm", "start"]
